name: Build autotracker

on:
  push:
    tags:
      - autotracker-*

jobs:
  parse-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      upload-url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: get-version
        run: tag=`git describe --exact-match --tags`; echo "version=${tag/autotracker-/}" >> "$GITHUB_OUTPUT"
      - uses: ncipollo/release-action@v1
        id: create-release
        with:
          draft: true

  build-autotracker-linux:
    runs-on: ubuntu-latest
    needs: parse-version
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -rf LADXR/gfx
      - run: mkdir -p ./pyevilemu/evilemu/ 
      - name: Create executable
        id: build
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
      - run: ${{ format('mv "{0}/magpie-autotracker" ./magpie-autotracker-linux', steps.build.outputs.executable_path) }}
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} magpie-autotracker-linux', github.ref_name) }}

  build-autotracker-windows:
    runs-on: windows-latest
    needs: parse-version
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -r -fo LADXR/gfx
      - name: Checkout pyevilemu
        uses: actions/checkout@v4
        with:
          repository: 'kbranch/pyevilemu'
          ref: 'magpie'
          path: 'pyevilemu'
      # - name: Build pyevilemu
      #   run: cd pyevilemu; python3 setup.py install
      - name: Create executable
        id: build
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
      - run: ${{ format('mv "{0}\magpie-autotracker.exe" .\magpie-autotracker-windows.exe', steps.build.outputs.executable_path) }}
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} magpie-autotracker-windows.exe', github.ref_name) }}

  build-autotracker-macos:
    runs-on: macos-latest
    needs: parse-version
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir -p ./pyevilemu/evilemu/ 
      - name: Remove LADXR gfx
        run: rm -rf LADXR/gfx
      - name: Create executable
        id: build
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
      - run: ${{ format('mv "{0}/magpie-autotracker" ./magpie-autotracker-macos', steps.build.outputs.executable_path) }}
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} magpie-autotracker-macos', github.ref_name) }}
